config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'posts#index'
  resources :posts, only: %i[new create index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :username, :password, :password_confirmation)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]

  def index
    @posts = Post.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/turbo_devise_controller.rb
# app/controllers/turbo_devise_controller.rb

class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p><%= notice %></p>
    <% end %>

    <% if flash[:alert] %>
      <p><%= alert %></p>
    <% end %>

    <header class="header">
      <h2><%= link_to "Members Only", root_path, class: "header__home-link" %></h2>
      <nav class="login-controls">
        <% if user_signed_in? %>
          <%= link_to current_user.username,
              edit_user_registration_path,
              class: 'btn btn--secondary'
          %>
          <%= button_to 'Logout',
              destroy_user_session_path,
              method: :delete,
              class: 'btn btn--secondary'
          %>
        <% else %>
          <%=
            link_to 'Sign In',
            new_user_session_path,
            class: 'btn btn--secondary'
          %>
          <%=
            link_to 'Sign Up',
            new_user_registration_path,
            class: 'btn btn--secondary'
          %>
        <% end %>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="post-heading">
  <h1>Posts</h1>
  <%= link_to 'Create New Post', new_post_path, class: 'btn btn--primary' %>
</div>

<ul class="post-container">
  <% @posts.each do |post| %>
    <li class="post">
      <h4 class="post__title">
        <%= post.title %>
      </h4>
      <div class="post__content">
        <p class="post__body">
          <%= post.body %>
        </p>
        <br>
        <p class="post__author">
          Created by: <%= user_signed_in? ? post.user.username : "Top Secret" %>
        </p>
      </div>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1 class="form-header">New Post</h1>

<%= form_with model: @post, html: { class: "form" } do |form| %>
  <div class="form__controls">
    <%= form.label :title, class: "form__label" %>
    <%= form.text_field :title, class: "form__text" %>
  </div>

  <div class="form__controls">
    <%= form.label :body, class: "form__label" %>
    <%= form.text_area :body, class: "form__textarea" %>
  </div>

  <div>
    <%= form.submit class: 'btn btn--primary' %>
  </div>
<% end %>